name: recycle
description: A collection of useful widgets
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  animations: ^2.0.1
  flutter:
    sdk: flutter
  image_picker: ^0.8.3+3
  intl: ^0.17.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: